#!/bin/bash
cd "${0%/*}"
# TODO Yatao: this is not good -- should retrieve the default path
# from the system. Currently some paths are missing -- dotnet etc.
# but I haven't found the file for specifying them!
export PATH="/usr/local/bin:/usr/bin:/bin/:usr/sbin:/sbin:$PATH"
./FVim $@
